name: PR name

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
    - main

jobs:
  check_name:
    name: Check PR name
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Naming Convention
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pattern="^feat\(#[0-9]+\) [A-Z].+"
          if [[ !$pr_title =~ $pattern ]]; then
            echo "Pull request title does not match the required pattern."
            echo "Title format should be: feat(#<pr-num>) <pr-full-title>"
            echo "Example: 'feat(#1) Add units'"
            exit 1
          fi